[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "d3-mcp-examples"
version = "0.1.0"
description = "Cube D3 MCP integration examples"
requires-python = ">=3.10"
